# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.2.97
    - 172.30.33.0/24

google_assistant:
  project_id: firehome-12954
  service_account: !include SERVICE_ACCOUNT.JSON
  report_state: true
  secure_devices_pin: "3514000"

utility_meter:
  wasmachine_wekelijks:
    name: "Wasmachine wekelijks"
    source: sensor.energy_consumption_today_28bc3
    cycle: weekly
  droger_wekelijks:
    name: "Droger wekelijks"
    source: sensor.energy_consumption_today_295d6
    cycle: weekly
  vriezer_wekelijks:
    name: "Vriezer wekelijks"
    source: sensor.energy_consumption_today_29544
    cycle: weekly

template:
  - sensor:
      - name: EnergyUnaccounted
        unique_id: EnergyUnaccounted
        unit_of_measurement: "W"
        state: '{{ states("sensor.power_consumed") |float(0) |round(2)
          - 217.7
          - states("sensor.power_usage_295d6") |float(0) |round(2)
          - states("sensor.power_usage_28bc3") |float(0) |round(2)
          - states("sensor.power_usage_29544") |float(0) |round(2)
          - states("sensor.power_usage_28c8f") |float(0) |round(2)
          - states("sensor.power_usage_2b3cc") |float(0) |round(2)
          - states("sensor.power_usage_28df8") |float(0) |round(2) }}'
        device_class: energy

sensor:
  - platform: template
    sensors:
      power_consumption:
        value_template: "{{ states('sensor.inverter_active_power') | float + states('sensor.power_actual') | float }}"
      power_inverter:
        value_template: "{{ 0 - states('sensor.inverter_active_power') | float }}"
